steps:
# Step 1: Delete Deployment Configurations
- name: 'google/cloud-sdk:latest'
  id: 'Delete Deployment Resources'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Deleting deployment resources..."
      if ! gcloud deploy releases delete --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --quiet; then
        echo "Failed to delete deployment releases"
        exit 1
      fi
      if ! gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1 --delete; then
        echo "Failed to delete pipeline configuration"
        exit 1
      fi
      if ! gcloud deploy apply --file deploy/dev.yaml --region=us-central1 --delete; then
        echo "Failed to delete dev configuration"
        exit 1
      fi

# Additional step to verify or apply new configurations, if needed
- name: 'google/cloud-sdk:latest'
  id: 'Apply New Configurations'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Applying new deployment configurations..."
      gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
      gcloud deploy apply --file deploy/dev.yaml --region=us-central1
      echo "Creating new release..."
      gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml
  waitFor: ['Delete Deployment Resources']

options:
  logging: CLOUD_LOGGING_ONLY
