steps:
# Step 1: Delete Docker Images
- name: 'google/cloud-sdk:latest'
  id: 'Delete Docker Images'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Deleting Docker images from registry..."
      if ! gcloud container images delete --force-delete-tags gcr.io/velvety-accord-430502-f0/python-app1:latest --quiet; then
        echo "Failed to delete Docker image"
        exit 1
      fi
  waitFor: ['-']

# Step 2: Delete Deployment Configurations
- name: 'google/cloud-sdk:latest'
  id: 'Delete Deployment Resources'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Deleting deployment resources..."
      if ! gcloud deploy releases delete --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --quiet; then
        echo "Failed to delete deployment releases"
        exit 1
      fi
      if ! gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1 --delete; then
        echo "Failed to delete pipeline configuration"
        exit 1
      fi
      if ! gcloud deploy apply --file deploy/dev.yaml --region=us-central1 --delete; then
        echo "Failed to delete dev configuration"
        exit 1
      fi
  waitFor: ['Delete Docker Images']

options:
  logging: CLOUD_LOGGING_ONLY
