steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build Docker Image'
  args:
    - 'build'
    - '--no-cache'  # Force a fresh build
    - '-t'
    - 'gcr.io/velvety-accord-430502-f0/python-app1:latest'
    - 'pythonapp'
  waitFor: ['-']  # Ensure this step completes before moving to the next

# Push Docker Image to Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push Docker Image'
  args:
    - 'push'
    - 'gcr.io/velvety-accord-430502-f0/python-app1:latest'
  waitFor: ['Build Docker Image']  # Ensure image is built before pushing

# Deployment Steps
- name: 'google/cloud-sdk:latest'
  id: 'Deploy to Google Cloud'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      echo "Applying deployment configurations..."
      gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
      gcloud deploy apply --file deploy/dev.yaml --region=us-central1
      echo "Creating release..."
      gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml
  waitFor: ['Push Docker Image']

options:
  logging: CLOUD_LOGGING_ONLY
