steps:
 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--no-cache', '-t', 'gcr.io/velvety-accord-430502-f0/python-app1:latest', '.']
images:
- 'gcr.io/velvety-accord-430502-f0/python-app1:latest'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/velvety-accord-430502-f0/python-app1', './pythonapp' ]
  id: 'Build Docker Image'

  # images:
  # - 'us-central1-docker.pkg.dev/<your_project_id>/gke-repo/quickstart-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/velvety-accord-430502-f0/pyhton-app1' ]
  id: 'Push Docker Image'

#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '-t', 'us-central1-docker.pkg.dev/velvety-accord-430502-f0/gke-repo/flask-image', './app2' ]
 # id: 'Build Docker Image2'

  # images:
  # - 'us-central1-docker.pkg.dev/<your_project_id>/gke-repo/quickstart-image'

#- name: 'gcr.io/cloud-builders/docker'
 # args: ['push', 'us-central1-docker.pkg.dev/velvety-accord-430502-f0/gke-repo/flask-image' ]
 # id: 'Push Docker Image2'


- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1
    gcloud deploy apply --file deploy/dev.yaml --region=us-central1
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY
