steps:
# Step 1: List and Delete YAML Files in Google Cloud Storage
- name: 'google/cloud-sdk:latest'
  id: 'Delete YAML Files from GCS'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Deleting YAML files from Google Cloud Storage..."
      # Specify the bucket name
      BUCKET_NAME="your-bucket-name"
      
      # List YAML files and delete them
      YAML_FILES=$(gsutil ls "gs://$BUCKET_NAME/**/*.yaml")
      for FILE in $YAML_FILES; do
        if gsutil rm "$FILE"; then
          echo "Successfully deleted YAML file: $FILE"
        else
          echo "Failed to delete YAML file: $FILE"
          exit 1
        fi
      done

# Step 2: Delete YAML Files from Local Directory (if applicable)
- name: 'google/cloud-sdk:latest'
  id: 'Delete Local YAML Files'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Deleting YAML files from local directory..."
      # Specify the directory path
      LOCAL_DIR="path/to/your/local/directory"
      
      # Find and delete YAML files
      find "$LOCAL_DIR" -type f -name "*.yaml" -exec rm -f {} \;
      echo "All YAML files deleted from local directory."

# Step 3: Clean Up Additional Resources (if needed)
- name: 'google/cloud-sdk:latest'
  id: 'Clean Up Additional Resources'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Performing additional clean-up tasks..."
      # Add additional clean-up commands here
      # For example, you might want to clean up directories, files, etc.
      # Customize as needed
  waitFor: ['Delete Local YAML Files']

options:
  logging: CLOUD_LOGGING_ONLY
