steps:
# Step 1: Delete Docker Images
- name: 'google/cloud-sdk:latest'
  id: 'Delete Docker Images'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Print commands and their arguments as they are executed
      echo "Deleting Docker images from registry..."
      gcloud container images delete --force-delete-tags gcr.io/velvety-accord-430502-f0/python-app1:latest --quiet
  waitFor: ['-']

# Step 2: Delete Deployment Configurations
- name: 'google/cloud-sdk:latest'
  id: 'Delete Deployment Resources'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Print commands and their arguments as they are executed
      echo "Deleting deployment resources..."
      gcloud deploy releases delete --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --quiet
      gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1 --delete
      gcloud deploy apply --file deploy/dev.yaml --region=us-central1 --delete
  waitFor: ['Delete Docker Images']

options:
  logging: CLOUD_LOGGING_ONLY
