steps:
# Step 1: Delete Docker Images
- name: 'google/cloud-sdk:latest'
  id: 'Delete Docker Images'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Deleting Docker images from Google Container Registry..."
      # Delete Docker images
      if ! gcloud container images delete --force-delete-tags gcr.io/velvety-accord-430502-f0/python-app1:latest --quiet; then
        echo "Failed to delete Docker image"
        exit 1
      fi

# Step 2: Delete Deployment Configurations
- name: 'google/cloud-sdk:latest'
  id: 'Delete Deployment Resources'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Deleting deployment resources..."
      # Delete deployment releases
      if ! gcloud deploy releases delete --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --quiet; then
        echo "Failed to delete deployment releases"
        exit 1
      fi
      # Delete deployment configurations
      if ! gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1 --delete; then
        echo "Failed to delete pipeline configuration"
        exit 1
      fi
      if ! gcloud deploy apply --file deploy/dev.yaml --region=us-central1 --delete; then
        echo "Failed to delete dev configuration"
        exit 1
      fi

# Optional Step: Clean Up Any Additional Resources
- name: 'google/cloud-sdk:latest'
  id: 'Clean Up Additional Resources'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Performing additional clean-up tasks..."
      # Add commands for any other clean-up tasks here
      # For example, deleting logs or other resources
  waitFor: ['Delete Deployment Resources']

options:
  logging: CLOUD_LOGGING_ONLY
