steps:
# Step 1: Delete Deployment Configurations
- name: 'google/cloud-sdk:latest'
  id: 'Delete Deployment Resources'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Deleting deployment resources..."
      # Delete deployment releases
      if ! gcloud deploy releases delete --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --quiet; then
        echo "Failed to delete deployment releases"
        exit 1
      fi
      # Delete deployment configurations
      if ! gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1 --delete; then
        echo "Failed to delete pipeline configuration"
        exit 1
      fi
      if ! gcloud deploy apply --file deploy/dev.yaml --region=us-central1 --delete; then
        echo "Failed to delete dev configuration"
        exit 1
      fi

# Optional: Step to Apply New Configurations
- name: 'google/cloud-sdk:latest'
  id: 'Apply New Configurations'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      set -x  # Enable debugging
      echo "Applying new deployment configurations..."
      if ! gcloud deploy apply --file deploy/pipeline.yaml --region=us-central1; then
        echo "Failed to apply pipeline configuration"
        exit 1
      fi
      if ! gcloud deploy apply --file deploy/dev.yaml --region=us-central1; then
        echo "Failed to apply dev configuration"
        exit 1
      fi
      echo "Creating new release..."
      if ! gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=us-central1 --skaffold-file=skaffold.yaml; then
        echo "Failed to create release"
        exit 1
      fi
  waitFor: ['Delete Deployment Resources']

options:
  logging: CLOUD_LOGGING_ONLY
