---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "app-python"
  namespace: "default"
  labels:
    app: "app-python"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "app-python"
  template:
    metadata:
      labels:
        app: "app-python"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "app-python-hpa-jotl"
  namespace: "default"
  labels:
    app: "app-python"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "app-python"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
